const phrases=["Kapazität","Akquise","Klopft!!","Antrag","Dankenswerterweise","Struktur","Ordnerstruktur","Effizienz","Jour fixe","Mitdenken","Prio","Abholen","Ich erwarte","Klar??","Hallo??","Unmöglich","Es kann nicht sein","Hut auf","Das stimmt nicht","Nein!!","Angebot","Weihnachts...","Nochmal!...","Home Office","So!","Deadline","Stakeholder","Performance"];
const $=s=>document.querySelector(s), board=$('#board'), start=$('#start'), game=$('#game'), info=$('#info'), win=$('#win');
let winningLine=null;
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function newGame(mode){winningLine=null;$('#protocolBtn').classList.remove('show');board.innerHTML='';const chosen=shuffle(phrases).slice(0,24);let p=0;for(let i=0;i<25;i++){const b=document.createElement('button');b.className='tile';b.dataset.i=i;if(i===12){b.classList.add('joker','checked');b.innerHTML='<div class="penguin" aria-label="Pinguin-Joker"></div>'}else{const text=chosen[p++];b.dataset.phrase=text;b.innerHTML=`<span>${text}</span>`;b.addEventListener('click',()=>{if(winningLine)return;b.classList.toggle('checked');const line=getWin();if(line)markWin(line)})}board.appendChild(b)}if(mode==='jourFixe'){const candidates=shuffle([...board.children].filter((_,i)=>i!==12));candidates.slice(0,3).forEach(tile=>{tile.className='tile joker checked';tile.dataset.phrase='Pinguin-Joker';tile.innerHTML='<div class="penguin" aria-label="Pinguin-Joker"></div>';tile.replaceWith(tile.cloneNode(true))})}start.classList.remove('active');game.classList.add('active')}
function checked(r,c){return board.children[r*5+c]?.classList.contains('checked')}
function getWin(){for(let r=0;r<5;r++)if([...Array(5)].every((_,c)=>checked(r,c)))return [...Array(5)].map((_,c)=>r*5+c);for(let c=0;c<5;c++)if([...Array(5)].every((_,r)=>checked(r,c)))return [...Array(5)].map((_,r)=>r*5+c);if([...Array(5)].every((_,i)=>checked(i,i)))return [0,6,12,18,24];if([...Array(5)].every((_,i)=>checked(i,4-i)))return [4,8,12,16,20];return null}
function markWin(line){winningLine=line;line.forEach(i=>board.children[i].classList.add('winner'));$('#protocolBtn').classList.add('show')}
function showWin(){const list=$('#protocolList');list.innerHTML='';winningLine.forEach(i=>{const tile=board.children[i];const li=document.createElement('li');li.textContent='✓ '+(tile.dataset.phrase||'Pinguin-Joker');list.appendChild(li)});win.classList.add('open');win.setAttribute('aria-hidden','false')}
$('#jourFixeBtn').onclick=()=>newGame('jourFixe');$('#grossmeetingBtn').onclick=()=>newGame('grossmeeting');$('#infoBtn').onclick=()=>{info.classList.add('open');info.setAttribute('aria-hidden','false')};$('[data-close]').onclick=()=>{info.classList.remove('open');info.setAttribute('aria-hidden','true')};$('#backBtn').onclick=()=>{game.classList.remove('active');start.classList.add('active')};$('#protocolBtn').onclick=showWin;$('#winClose').onclick=()=>{win.classList.remove('open');win.setAttribute('aria-hidden','true');game.classList.remove('active');start.classList.add('active')};
